### ISSUE TITLE
ch15 pymc3 traceplot result is different from the book

### ISSUE THREAD

**Issue by junkwhinger** [mfenner1/mlwpy_code#1]
Hi, 

I found some discrepancies in ch15 traceplot result between the book and your code.
Can you kindly tell me how to replicate the graph shown in the book?

Thank you.

**Comment by mfenner1** [comment]
@junkwhinger Sorry for the delay in responding.  I didn't see a notification for this.  My first (quick, unresearched) guess is that there is randomness in pymc3 that isn't controlled through the NumPy random seed that I set in the mlwpy.py utility file.  Since PyMC3 uses Theano under the hood, to get reproducible pseudo-randomness, we would have to set a random seed either in the pymc3 or theano space.  I never considered that.  I'll look into updating the code to make that 100% reproducible.

**Comment by mfenner1** [comment]
In the process of pushing a new update, I added pymc3 specific random_seeds.  Should address this issue.
