### ISSUE TITLE
Chapter 3. Where are the 'target_names'  and target column ?

### ISSUE THREAD

**Issue by DavidAKZ** [mfenner1/mlwpy_code#8]
I'm using the following code to replicate the figure on p59 of the book

    from sklearn.datasets import load_iris
    import pandas as pd
    import matplotlib.pyplot as plt
    import seaborn as sns

    import numpy as np

    iris = load_iris()
    iris_df = pd.DataFrame(iris.data, columns =iris.feature_names)
    iris_df['target'] = iris.target

    sns.pairplot(iris_df, hue='target', height=1.7, palette = 'tab20')

<img width="1280" alt="Screen Shot 2021-07-21 at 10 47 54 am" src="https://user-images.githubusercontent.com/8805781/126415316-12931b9f-b2ce-44f2-a604-c8a437543286.png">

My question is, how do I replicate the figure with the fifth column as shown in the book , unlike the enclosed image ? Also, is it possible to display the target_names in the figure thanks ?

**Comment by mfenner1** [comment]
Interesting.  I'm guessing that there is a version difference between the seaborn used in the book and more recent versions.  To get target names from 0, 1, 2 to setosa, versicolor, virginica we can either remap the target column using pandas (look at `.map` and `.replace`) -or- when you make the assignment `iris_df['target']` you could use the symbolic names instead of the numeric values with `iris_df['target'] = iris.target_names[iris.target]` (untested) or something close.
